// The things a crawler reads, checked against each other.
//
// None of this is game logic, and it is here anyway for one reason: every
// failure this catches is invisible. A page with no canonical still renders. A
// page missing from the sitemap still works. The site looks perfect and is
// quietly unfindable, and nobody notices for a month.
//
// The sitemap itself is generated by the Worker (src/index.js) and cannot be
// fetched from a plain static server, so these read its PAGES list out of the
// source and compare that against what the pages themselves claim. Same drift,
// caught the same way — and it is the exact drift that had already happened:
// tiles.html shipped with a canonical and was never added to the list.

import { test, assert, eq } from "./harness.js";

const PUBLIC_PAGES = ["index", "game", "rulebook", "tiles", "credits"];

const html = Object.fromEntries(
  await Promise.all(
    PUBLIC_PAGES.map(async (name) => [name, await fetch(`../${name}.html`).then((r) => r.text())]),
  ),
);
const worker = await fetch("../src/index.js").then((r) => r.text());

const meta = (doc, name) => (doc.match(new RegExp(`name="${name}" content="([^"]*)"`)) || [])[1] || null;
const tag = (doc, re) => (doc.match(re) || [])[1] || null;

// The Worker builds its sitemap from these three constants; read them rather
// than restating the URLs, so the test cannot drift from the thing it checks.
const PREFIX = tag(worker, /const PREFIX = "(.*?)"/);
const ORIGIN = tag(worker, /const ORIGIN = "(.*?)"/);
const PAGES = tag(worker, /const PAGES = \[(.*?)\]/)
  .split(",")
  .map((p) => p.trim().replace(/^"|"$/g, ""));
const ROOT = `${ORIGIN}${PREFIX}/`;

test("seo: every public page has a title and a description", () => {
  for (const name of PUBLIC_PAGES) {
    const title = tag(html[name], /<title>(.*?)<\/title>/);
    assert(title && title.length > 10, `${name} has a real title`);
    const desc = meta(html[name], "description");
    assert(desc && desc.length > 50, `${name} has a real description`);
    // Past roughly 160 characters a result snippet is cut mid-sentence, which
    // is worse than a shorter one that ends where it meant to.
    assert(desc.length <= 165, `${name} description fits a snippet (${desc.length})`);
  }
});

test("seo: no two pages claim the same title", () => {
  const titles = PUBLIC_PAGES.map((n) => tag(html[n], /<title>(.*?)<\/title>/));
  eq(new Set(titles).size, titles.length, "duplicate titles compete with each other");
});

test("seo: every page canonicalises to itself", () => {
  for (const name of PUBLIC_PAGES) {
    const canonical = tag(html[name], /rel="canonical" href="([^"]*)"/);
    assert(canonical, `${name} has a canonical`);
    const expected = name === "index" ? ROOT : ROOT + name;
    eq(canonical, expected, `${name} canonical`);
  }
});

// The one that had already gone wrong.
test("seo: the sitemap lists exactly the pages that exist", () => {
  const listed = PAGES.map((p) => ROOT + p).sort();
  const claimed = PUBLIC_PAGES.map((n) => tag(html[n], /rel="canonical" href="([^"]*)"/)).sort();
  eq(listed, claimed, "sitemap and canonicals must be the same set");
});

test("seo: og:url agrees with the canonical", () => {
  for (const name of PUBLIC_PAGES) {
    const canonical = tag(html[name], /rel="canonical" href="([^"]*)"/);
    const og = tag(html[name], /property="og:url" content="([^"]*)"/);
    eq(og, canonical, `${name} og:url`);
  }
});

test("seo: the social card is an absolute URL on every page", () => {
  for (const name of PUBLIC_PAGES) {
    const img = tag(html[name], /property="og:image" content="([^"]*)"/);
    assert(img && img.startsWith("https://"), `${name} og:image is absolute`);
    assert(tag(html[name], /property="og:image:alt" content="([^"]*)"/), `${name} og:image:alt`);
  }
});

test("seo: structured data parses", () => {
  for (const name of PUBLIC_PAGES) {
    const blocks = html[name].match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g) || [];
    assert(blocks.length > 0, `${name} has structured data`);
    for (const block of blocks) {
      const json = block.replace(/<\/?script[^>]*>/g, "");
      const parsed = JSON.parse(json); // throws, which is the assertion
      assert(parsed["@context"] === "https://schema.org", `${name} names the vocabulary`);
      assert(parsed["@type"], `${name} names a type`);
    }
  }
});

test("seo: every page can be reached from every other", () => {
  for (const name of PUBLIC_PAGES) {
    // The menu is the hub, so it is the one link every page must carry.
    assert(/href="index\.html"/.test(html[name]) || name === "index", `${name} links home`);
  }
  for (const name of PUBLIC_PAGES.filter((n) => n !== "index")) {
    assert(/href="[a-z]+\.html"/.test(html.index), "the menu links out");
  }
});
