// The things a crawler reads, checked against each other.
//
// None of this is game logic, and it is here anyway for one reason: every
// failure this catches is invisible. A page with no canonical still renders. A
// page missing from the sitemap still works. The site looks perfect and is
// quietly unfindable, and nobody notices for a month.
//
// The sitemap itself is generated by the Worker (src/index.js) and cannot be
// fetched from a plain static server, so these read its PAGES list out of the
// source and compare that against what the pages themselves claim. Same drift,
// caught the same way — and it is the exact drift that had already happened:
// tiles.html shipped with a canonical and was never added to the list.

import { test, assert, eq, suite } from "./harness.js";
// The languages the site actually ships, from the module that decides it.
// Listed here instead, this guard would go stale the day a third one lands —
// which is the same drift it exists to catch, one level up.
import { LANGS } from "../js/lang.js";

// Which copy of this suite is speaking. Stamped by tools/record_shell.py;
// report() compares it against the file on disk, so a stale module is caught
// even when the test count happens to match.
suite(import.meta.url, "d1b84ae6");

const PUBLIC_PAGES = ["index", "game", "rulebook", "tiles", "credits"];

// no-store: these assert about files on disk, and a cached copy of the file
// you are checking is how a fixed page keeps reporting the old fault.
const NO_STORE = { cache: "no-store" };

const html = Object.fromEntries(
  await Promise.all(
    PUBLIC_PAGES.map(async (name) => [name, await fetch(`../${name}.html`, NO_STORE).then((r) => r.text())]),
  ),
);
const worker = await fetch("../src/index.js", NO_STORE).then((r) => r.text());

// Read out of the Worker source, the same way PAGES is. One flag, one place.
const SHIPPED = /export const SHIPPED\s*=\s*true/.test(worker);

const meta = (doc, name) => (doc.match(new RegExp(`name="${name}" content="([^"]*)"`)) || [])[1] || null;
const tag = (doc, re) => (doc.match(re) || [])[1] || null;

// The Worker builds its sitemap from these three constants; read them rather
// than restating the URLs, so the test cannot drift from the thing it checks.
const PREFIX = tag(worker, /const PREFIX = "(.*?)"/);
const ORIGIN = tag(worker, /const ORIGIN = "(.*?)"/);
const PAGES = tag(worker, /const PAGES = \[(.*?)\]/)
  .split(",")
  .map((p) => p.trim().replace(/^"|"$/g, ""));
const ROOT = `${ORIGIN}${PREFIX}/`;

test("seo: every public page has a title and a description", () => {
  for (const name of PUBLIC_PAGES) {
    const title = tag(html[name], /<title>(.*?)<\/title>/);
    assert(title && title.length > 10, `${name} has a real title`);
    const desc = meta(html[name], "description");
    assert(desc && desc.length > 50, `${name} has a real description`);
    // Past roughly 160 characters a result snippet is cut mid-sentence, which
    // is worse than a shorter one that ends where it meant to.
    assert(desc.length <= 165, `${name} description fits a snippet (${desc.length})`);
  }
});

test("seo: no two pages claim the same title", () => {
  const titles = PUBLIC_PAGES.map((n) => tag(html[n], /<title>(.*?)<\/title>/));
  eq(new Set(titles).size, titles.length, "duplicate titles compete with each other");
});

test("seo: every page canonicalises to itself", () => {
  for (const name of PUBLIC_PAGES) {
    const canonical = tag(html[name], /rel="canonical" href="([^"]*)"/);
    assert(canonical, `${name} has a canonical`);
    const expected = name === "index" ? ROOT : ROOT + name;
    eq(canonical, expected, `${name} canonical`);
  }
});

// The one that had already gone wrong.
test("seo: the sitemap lists exactly the pages that exist", () => {
  const listed = PAGES.map((p) => ROOT + p).sort();
  const claimed = PUBLIC_PAGES.map((n) => tag(html[n], /rel="canonical" href="([^"]*)"/)).sort();
  eq(listed, claimed, "sitemap and canonicals must be the same set");
});

test("seo: og:url agrees with the canonical", () => {
  for (const name of PUBLIC_PAGES) {
    const canonical = tag(html[name], /rel="canonical" href="([^"]*)"/);
    const og = tag(html[name], /property="og:url" content="([^"]*)"/);
    eq(og, canonical, `${name} og:url`);
  }
});

test("seo: the social card is an absolute URL on every page", () => {
  for (const name of PUBLIC_PAGES) {
    const img = tag(html[name], /property="og:image" content="([^"]*)"/);
    assert(img && img.startsWith("https://"), `${name} og:image is absolute`);
    assert(tag(html[name], /property="og:image:alt" content="([^"]*)"/), `${name} og:image:alt`);
  }
});

test("seo: structured data parses", () => {
  for (const name of PUBLIC_PAGES) {
    const blocks = html[name].match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g) || [];
    assert(blocks.length > 0, `${name} has structured data`);
    for (const block of blocks) {
      const json = block.replace(/<\/?script[^>]*>/g, "");
      const parsed = JSON.parse(json); // throws, which is the assertion
      assert(parsed["@context"] === "https://schema.org", `${name} names the vocabulary`);
      assert(parsed["@type"], `${name} names a type`);
    }
  }
});

// A FALSE STATEMENT PARSES PERFECTLY, which is why the test above did not catch
// this. "seo: structured data parses" asserts the JSON is well-formed and names
// a vocabulary; it has no opinion about whether any of it is true. inLanguage
// said "en" while the game had been fully playable in 繁體中文 at that URL for
// weeks — and with DETECT on since 2026-08-24 a Chinese browser is SENT to the
// Chinese version of a page whose own metadata calls itself English.
//
// DERIVED FROM js/lang.js, and the tag comes from there too rather than being
// spelled here. LANGS carries "zh-Hant-TW", which is also what stampDocument
// writes into <html lang>, so the page and its structured data make the same
// claim in the same words. A third language then fails this guard on the day it
// is added instead of quietly leaving the metadata a language short.
test("seo: the structured data names every language the site ships", () => {
  const tags = Object.values(LANGS).map((l) => l.tag);
  assert(tags.length >= 2,
    "js/lang.js exports fewer than two languages, so this guard is comparing " +
    "against nothing — if the site is monolingual again, delete it");

  const blocks = html.index.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g) || [];
  const games = blocks
    .map((b) => JSON.parse(b.replace(/<\/?script[^>]*>/g, "")))
    .filter((p) => p["@type"] === "VideoGame");
  eq(games.length, 1, "the landing page does not carry exactly one VideoGame block");

  const declared = [].concat(games[0].inLanguage || []);
  for (const t of tags) {
    assert(declared.indexOf(t) !== -1,
      "the VideoGame block does not name " + t + " in inLanguage (it says " +
      JSON.stringify(games[0].inLanguage) + "), so the page understates what it " +
      "is — js/lang.js ships that language and a browser asking for it is sent here");
  }
  for (const t of declared) {
    assert(tags.indexOf(t) !== -1,
      "inLanguage claims " + t + ", which js/lang.js does not ship — the page " +
      "is promising a language a reader cannot get");
  }
});

// THE ROOMS ARE IN THE SERVED MARKUP (#134).
//
// tiles.html used to ship 315 indexable characters: a heading, two intro
// paragraphs and two placeholders. Twenty rooms with names, in two languages,
// were all injected at load — so the most distinctive vocabulary the game owns
// existed nowhere a crawler or a reader without script could see it.
// tools/render_tiles.py writes the words in ahead of time; this checks they
// arrived and, more importantly, that they still MATCH.
//
// READ FROM theme.json, NEVER LISTED HERE. A guard with its own copy of the
// twenty names is a guard testing its own copy — it passes while the page and
// the data disagree, which is the drift the whole page exists to prevent. That
// drift is not hypothetical here: the intro read "sixteen rooms" for a while
// after the set had become twenty.
test("seo: the tiles page serves every room name, from the data (#134)", async () => {
  const [tiles, theme] = await Promise.all([
    fetch("../data/tiles.json", NO_STORE).then((r) => r.json()),
    fetch("../data/theme.json", NO_STORE).then((r) => r.json()),
  ]);
  const defs = [].concat(tiles.indoor || [], tiles.outdoor || []);
  const names = defs.map((d) => (theme.tiles || {})[d.id]).filter(Boolean);

  // 1. COUNT FIRST, so nothing below can pass on an empty haystack. "every name
  //    is present" is trivially true of no names at all.
  eq(defs.length, 20, "the tile set is no longer twenty tiles (" + defs.length + ")");
  eq(names.length, 20,
    "only " + names.length + " of the twenty tiles have a name in theme.json, so " +
    "this guard would be checking a short list against the page");

  // 2. Strip what a crawler does not read, so a name surviving only inside a
  //    comment or a <script> does not count as served.
  const served = html.tiles
    .replace(/<script[\s\S]*?<\/script>/g, " ")
    .replace(/<!--[\s\S]*?-->/g, " ");

  const missing = names.filter((n) => served.indexOf(n) === -1);
  eq(missing.length, 0,
    "tiles.html does not serve " + missing.length + " of the twenty room names — " +
    missing.join(", ") + ". Re-run: python tools/render_tiles.py");

  // 3. AND THE COUNT IN THE PROSE IS THE REAL ONE. This is the specific drift
  //    the intro was made dynamic for, so a pre-rendered page has to be held to
  //    it too — a build step that is not re-run is exactly how "sixteen" got
  //    there the first time.
  const words = ((theme.tilesPage || {}).words) || [];
  const spelled = words[defs.length];
  assert(spelled,
    "theme.json cannot spell " + defs.length + ", so the intro cannot be checked");
  const intro = /<p class="muted" id="tile-intro">([\s\S]*?)<\/p>/.exec(served);
  assert(intro, "tiles.html has no intro paragraph to check");
  assert(new RegExp(spelled, "i").test(intro[1]),
    "the served intro does not say " + spelled + " — it reads " +
    JSON.stringify(intro[1].trim().slice(0, 60)) + ". The tile set changed and " +
    "tools/render_tiles.py was not re-run, which is the drift this page exists " +
    "to prevent");
});

test("seo: every page can be reached from every other", () => {
  for (const name of PUBLIC_PAGES) {
    // The menu is the hub, so it is the one link every page must carry.
    assert(/href="index\.html"/.test(html[name]) || name === "index", `${name} links home`);
  }
  for (const name of PUBLIC_PAGES.filter((n) => n !== "index")) {
    assert(/href="[a-z]+\.html"/.test(html.index), "the menu links out");
  }
});

// The noindex has two failure modes and they point opposite ways, so one
// assertion cannot cover both: shipping WITH it leaves the game unfindable,
// and losing it BEFORE shipping puts a duplicate of Grave Errand's copy in
// front of the real game. Which bug is live depends only on whether the site
// has shipped, so the flag decides which way the test reads.
//
// This used to assert the post-ship half unconditionally, and failed by design
// for weeks. A suite with a permanent red teaches everyone to skim past red,
// which costs more than the check was worth — and it very nearly did: a stale
// two-test-short run went unquestioned on the same suite because one number
// among the noise looked normal.
test("seo: every public page's noindex matches the ship state", () => {
  for (const name of PUBLIC_PAGES) {
    const robots = meta(html[name], "robots") || "";
    const heldBack = /noindex/.test(robots);
    if (SHIPPED) {
      assert(!heldBack, `${name} still carries a noindex — the shipped site is invisible`);
    } else {
      assert(heldBack, `${name} has lost its noindex before ship — it will be indexed as a duplicate`);
    }
  }
});

// ---- The measurement tag -------------------------------------------------------
// Not SEO, but the same failure shape as everything above and it belongs with
// them: five hand-pasted copies of one hardcoded id, invisible when wrong. The
// sitemap already proved this project can ship four pages out of five and not
// notice.
const GA_ID = "G-Q4VS3P3T58";

test("analytics: every public page carries the tag, exactly once", () => {
  for (const name of PUBLIC_PAGES) {
    const loaders = (html[name].match(/googletagmanager\.com\/gtag\/js\?id=/g) || []).length;
    eq(loaders, 1, `${name} loads gtag once — twice double-counts every visit`);
    assert(html[name].includes(`gtag('config', '${GA_ID}')`), `${name} configures ${GA_ID}`);
  }
});

test("analytics: one property, not five", () => {
  const ids = PUBLIC_PAGES.flatMap((n) => html[n].match(/G-[A-Z0-9]+/g) || []);
  eq([...new Set(ids)], [GA_ID], "a stray id sends part of the traffic somewhere else");
});
