# -*- coding: utf-8 -*-
"""Write the tile gallery's WORDS into tiles.html ahead of time (#134).

WHY A BUILD STEP AND NOT THE WORKER, which was a real choice and not a detail.
src/index.js already serves this prefix and generates the sitemap, so rendering
on the way out would have worked and would have known the request. It is not
used, because a Worker that rewrites HTML at the edge makes the SHIPPED bytes
differ from the bytes tools/record_shell.py hashed — and that hash is the entire
basis of the shell digest and of the CACHE name derived from it. The digest
would then describe a file nobody is served, silently, and the one guard that
notices when the shell moves would be watching the wrong thing. A build step
keeps the served file byte-identical to the repo file, so everything downstream
of `git show HEAD:` stays true.

WHAT IS RENDERED, AND WHAT IS DELIBERATELY NOT.

Rendered: the intro sentence, both section headings with their notes and counts,
and all twenty room names. Every one of those is a direct lookup in
data/theme.json or a count of data/tiles.json.

NOT rendered: the per-tile sentences — the doors line, the chips and the notes.
Those are composed by noteFor() and chipsFor() in js/tiles.js from each tile's
own properties, and reproducing them here would be a SECOND IMPLEMENTATION of
that logic that drifts the first time either changes. The issue asked for the
words; these are the words that are data. If the per-tile sentences are wanted
in the served markup too, the honest way is to move that composition into
something both can read, which is its own piece of work.

THE COUNT IS COMPUTED, NEVER TYPED. The intro once read "sixteen rooms" after
the set had become twenty, which is why it is filled at load in the first place.
It is filled here from len(tiles) for the same reason, and the guard in
tests/seo.test.js compares the served names against theme.json so a stale
render fails rather than sits there looking authoritative.

Run it after changing data/tiles.json or data/theme.json:

    python tools/render_tiles.py
"""

import io
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BEGIN = "<!-- BEGIN generated by tools/render_tiles.py — do not edit by hand -->"
END = "<!-- END generated -->"


def read_json(rel):
    with io.open(os.path.join(ROOT, rel), encoding="utf-8") as fh:
        return json.load(fh)


def esc(text):
    return (text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def spell(n, words):
    """The theme's own number words, so the page spells numbers one way."""
    return words[n] if 0 <= n < len(words) else str(n)


def fill(template, values):
    out = template
    for key, val in values.items():
        out = out.replace("{" + key + "}", str(val))
    return out


def build():
    tiles = read_json("data/tiles.json")
    theme = read_json("data/theme.json")
    page = theme["tilesPage"]
    words = page["words"]
    names = theme["tiles"]

    indoor = tiles["indoor"]
    outdoor = tiles["outdoor"]
    total = len(indoor) + len(outdoor)

    intro = fill(page["intro"], {
        "total": spell(total, words).capitalize(),
        "inside": spell(len(indoor), words),
        "outside": spell(len(outdoor), words),
    })

    rows = [BEGIN]
    for group, title, note in (
        (indoor, page["indoor-title"], page["indoor-note"]),
        (outdoor, page["outdoor-title"], page["outdoor-note"]),
    ):
        rows.append('    <section class="tilesection">')
        rows.append("      <h2>%s</h2>" % esc(title))
        rows.append('      <p class="muted">%s</p>' % esc(note))
        rows.append('      <p class="muted">%s</p>'
                    % esc(fill(page["n-tiles"], {"n": len(group)})))
        rows.append("      <ul>")
        for d in group:
            rows.append("        <li>%s</li>" % esc(names.get(d["id"], d["id"])))
        rows.append("      </ul>")
        rows.append("    </section>")
    rows.append("    " + END)
    return intro, "\n".join(rows)


def splice(html, intro, block):
    # The intro paragraph carries the derived sentence instead of the loading
    # placeholder. js/tiles.js overwrites it on load exactly as before, so a
    # reader with script sees no difference; a reader without one now sees the
    # real sentence rather than "Counting the tile set…".
    start = html.index('<p class="muted" id="tile-intro">')
    stop = html.index("</p>", start) + len("</p>")
    html = html[:start] + '<p class="muted" id="tile-intro">%s</p>' % esc(intro) + html[stop:]

    open_at = html.index('<div id="gallery">')
    body_at = html.index(">", open_at) + 1
    close_at = html.index("</div>", body_at)
    inner = "\n" + block + "\n    "
    return html[:body_at] + inner + html[close_at:]


def main():
    path = os.path.join(ROOT, "tiles.html")
    with io.open(path, encoding="utf-8", newline="") as fh:
        html = fh.read()
    intro, block = build()
    out = splice(html, intro, block)
    if out == html:
        print("tiles.html already current")
        return 0
    with io.open(path, "w", encoding="utf-8", newline="") as fh:
        fh.write(out)
    rooms = out.count("<li>")
    print("tiles.html: %d room names written into the served markup" % rooms)
    return 0


if __name__ == "__main__":
    sys.exit(main())
